### ISSUE TITLE
VoLTE for Airtel India does not work on 1+3 device

### ISSUE THREAD

**Issue by rdx124** [PixelExperience-Devices/device_oneplus_sm8150-common#2]
I was on pixel experience 9 when I ported my number to Airtel India. The device didn't show me volte option in settings. I thought it could be the issue with Airtel, but that sim was working fine on my iPhone with volte calls.
I upgraded pixel experience to 10, now I could see the menu to enable / disable volte but the calls are not being placed over VoLTE be whatever the settings of enable volte in settings. 
![Screenshot_20200816-123738435](https://user-images.githubusercontent.com/13104014/90514076-494af700-e17e-11ea-89fb-54493e27640b.jpg)
![Screenshot_20200816-125255419](https://user-images.githubusercontent.com/13104014/90514093-510a9b80-e17e-11ea-9434-2080ae8e3049.jpg)

I had three days working sessions with Airtel and they said it's all fine on their end, which really is, because iPhone was placing volte calls on the same sim.

Let me know what and how can I provide more data for your rectification. 

Thanks. This is a great rom I don't want to switch out of ever.

**Comment by rocketeer231** [comment]
Not related to OnePlus 3 Series. It is Snapdragon 855 devices repo

**Comment by rdx124** [comment]
Can you help me move this to relevant repository? Because I am on oneplus 3, and really not sure which repo this should be reported to. I found this repository named oneplus and I am facing issue on oneplus device. 

Thanks.

**Comment by itsjoeoui** [comment]
> Can you help me move this to relevant repository? Because I am on oneplus 3, and really not sure which repo this should be reported to. I found this repository named oneplus and I am facing issue on oneplus device.
> 
> Thanks.

https://github.com/PixelExperience-Devices/device_oneplus_oneplus3
